import React, { useState } from 'react';
import cl from './Content.module.scss';
import ContentBattingTable from '../ContentBattingTable/ContentBattingTable';
import ContentPitchingTable from '../ContentPitchingTable/ContentPitchingTable';
import Dropdown from 'components/UI/dropdown/GamesDropdown/Dropdown';

const Content = ({ games, playerYears }) => {
  const [tableType, setTableType] = useState('Batting');

  const TABLE_DATA = {
    batting: [
      {
        year: '0000',
        league: 'Name League',
        game: '01 sep, Name team - Name Team',
        ab: 0,
        h: 0,
        '2b': 0,
        '3b': 0,
        hr: 0,
        rbi: 0,
        gdp: 0,
        bb: 0,
        hp: 0,
        sh: 0,
        sf: 0,
        so: 0,
        tb: 0,
        avg: 0,
        slg: 0,
        obp: 0,
        ops: 0,
        ch: 0,
        po: 0,
        a: 0,
        e: 0,
        dp: 0,
        'fld%': 0,
        sb: 0,
        cs: 0,
        '%sb': 0,
        lob: 0
      },
      {
        year: '0000',
        league: 'Name League',
        game: '01 sep, Name team - Name Team',
        ab: 0,
        h: 0,
        '2b': 0,
        '3b': 0,
        hr: 0,
        rbi: 0,
        gdp: 0,
        bb: 0,
        hp: 0,
        sh: 0,
        sf: 0,
        so: 0,
        tb: 0,
        avg: 0,
        slg: 0,
        obp: 0,
        ops: 0,
        ch: 0,
        po: 0,
        a: 0,
        e: 0,
        dp: 0,
        'fld%': 0,
        sb: 0,
        cs: 0,
        '%sb': 0,
        lob: 0
      },
      {
        year: '0000',
        league: 'Name League',
        game: '01 sep, Name team - Name Team',
        ab: 0,
        h: 0,
        '2b': 0,
        '3b': 0,
        hr: 0,
        rbi: 0,
        gdp: 0,
        bb: 0,
        hp: 0,
        sh: 0,
        sf: 0,
        so: 0,
        tb: 0,
        avg: 0,
        slg: 0,
        obp: 0,
        ops: 0,
        ch: 0,
        po: 0,
        a: 0,
        e: 0,
        dp: 0,
        'fld%': 0,
        sb: 0,
        cs: 0,
        '%sb': 0,
        lob: 0
      },
      {
        year: '0000',
        league: 'Name League',
        game: '01 sep, Name team - Name Team',
        ab: 0,
        h: 0,
        '2b': 0,
        '3b': 0,
        hr: 0,
        rbi: 0,
        gdp: 0,
        bb: 0,
        hp: 0,
        sh: 0,
        sf: 0,
        so: 0,
        tb: 0,
        avg: 0,
        slg: 0,
        obp: 0,
        ops: 0,
        ch: 0,
        po: 0,
        a: 0,
        e: 0,
        dp: 0,
        'fld%': 0,
        sb: 0,
        cs: 0,
        '%sb': 0,
        lob: 0
      },
      {
        year: '0000',
        league: 'Name League',
        game: '01 sep, Name team - Name Team',
        ab: 0,
        h: 0,
        '2b': 0,
        '3b': 0,
        hr: 0,
        rbi: 0,
        gdp: 0,
        bb: 0,
        hp: 0,
        sh: 0,
        sf: 0,
        so: 0,
        tb: 0,
        avg: 0,
        slg: 0,
        obp: 0,
        ops: 0,
        ch: 0,
        po: 0,
        a: 0,
        e: 0,
        dp: 0,
        'fld%': 0,
        sb: 0,
        cs: 0,
        '%sb': 0,
        lob: 0
      },
      {
        year: '0000',
        league: 'Name League',
        game: '01 sep, Name team - Name Team',
        ab: 0,
        h: 0,
        '2b': 0,
        '3b': 0,
        hr: 0,
        rbi: 0,
        gdp: 0,
        bb: 0,
        hp: 0,
        sh: 0,
        sf: 0,
        so: 0,
        tb: 0,
        avg: 0,
        slg: 0,
        obp: 0,
        ops: 0,
        ch: 0,
        po: 0,
        a: 0,
        e: 0,
        dp: 0,
        'fld%': 0,
        sb: 0,
        cs: 0,
        '%sb': 0,
        lob: 0
      },
      {
        year: '0000',
        league: 'Name League',
        game: '01 sep, Name team - Name Team',
        ab: 0,
        h: 0,
        '2b': 0,
        '3b': 0,
        hr: 0,
        rbi: 0,
        gdp: 0,
        bb: 0,
        hp: 0,
        sh: 0,
        sf: 0,
        so: 0,
        tb: 0,
        avg: 0,
        slg: 0,
        obp: 0,
        ops: 0,
        ch: 0,
        po: 0,
        a: 0,
        e: 0,
        dp: 0,
        'fld%': 0,
        sb: 0,
        cs: 0,
        '%sb': 0,
        lob: 0
      },
      {
        year: '0000',
        league: 'Name League',
        game: '01 sep, Name team - Name Team',
        ab: 0,
        h: 0,
        '2b': 0,
        '3b': 0,
        hr: 0,
        rbi: 0,
        gdp: 0,
        bb: 0,
        hp: 0,
        sh: 0,
        sf: 0,
        so: 0,
        tb: 0,
        avg: 0,
        slg: 0,
        obp: 0,
        ops: 0,
        ch: 0,
        po: 0,
        a: 0,
        e: 0,
        dp: 0,
        'fld%': 0,
        sb: 0,
        cs: 0,
        '%sb': 0,
        lob: 0
      },
      {
        year: '0000',
        league: 'Name League',
        game: '01 sep, Name team - Name Team',
        ab: 0,
        h: 0,
        '2b': 0,
        '3b': 0,
        hr: 0,
        rbi: 0,
        gdp: 0,
        bb: 0,
        hp: 0,
        sh: 0,
        sf: 0,
        so: 0,
        tb: 0,
        avg: 0,
        slg: 0,
        obp: 0,
        ops: 0,
        ch: 0,
        po: 0,
        a: 0,
        e: 0,
        dp: 0,
        'fld%': 0,
        sb: 0,
        cs: 0,
        '%sb': 0,
        lob: 0
      },
      {
        year: '0000',
        league: 'Name League',
        game: '01 sep, Name team - Name Team',
        ab: 0,
        h: 0,
        '2b': 0,
        '3b': 0,
        hr: 0,
        rbi: 0,
        gdp: 0,
        bb: 0,
        hp: 0,
        sh: 0,
        sf: 0,
        so: 0,
        tb: 0,
        avg: 0,
        slg: 0,
        obp: 0,
        ops: 0,
        ch: 0,
        po: 0,
        a: 0,
        e: 0,
        dp: 0,
        'fld%': 0,
        sb: 0,
        cs: 0,
        '%sb': 0,
        lob: 0
      }
    ],
    pitching: [
			{
        year: '0000',
        league: 'Name League',
        game: '01 sep, Name team - Name Team',
        pa: 0,
        r: 0,
        er: 0,
        h: 0,
        '2b': 0,
        '3b': 0,
        hr: 0,
        bb: 0,
        ibb: 0,
        hp: 0,
        sh: 0,
        sf: 0,
        so: 0,
        wp: 0,
        era: 0,
        np: 0,
        ns: 0,
        nb: 0
      },
			{
        year: '0000',
        league: 'Name League',
        game: '01 sep, Name team - Name Team',
        pa: 0,
        r: 0,
        er: 0,
        h: 0,
        '2b': 0,
        '3b': 0,
        hr: 0,
        bb: 0,
        ibb: 0,
        hp: 0,
        sh: 0,
        sf: 0,
        so: 0,
        wp: 0,
        era: 0,
        np: 0,
        ns: 0,
        nb: 0
      },
			{
        year: '0000',
        league: 'Name League',
        game: '01 sep, Name team - Name Team',
        pa: 0,
        r: 0,
        er: 0,
        h: 0,
        '2b': 0,
        '3b': 0,
        hr: 0,
        bb: 0,
        ibb: 0,
        hp: 0,
        sh: 0,
        sf: 0,
        so: 0,
        wp: 0,
        era: 0,
        np: 0,
        ns: 0,
        nb: 0
      },
			{
        year: '0000',
        league: 'Name League',
        game: '01 sep, Name team - Name Team',
        pa: 0,
        r: 0,
        er: 0,
        h: 0,
        '2b': 0,
        '3b': 0,
        hr: 0,
        bb: 0,
        ibb: 0,
        hp: 0,
        sh: 0,
        sf: 0,
        so: 0,
        wp: 0,
        era: 0,
        np: 0,
        ns: 0,
        nb: 0
      },
			{
        year: '0000',
        league: 'Name League',
        game: '01 sep, Name team - Name Team',
        pa: 0,
        r: 0,
        er: 0,
        h: 0,
        '2b': 0,
        '3b': 0,
        hr: 0,
        bb: 0,
        ibb: 0,
        hp: 0,
        sh: 0,
        sf: 0,
        so: 0,
        wp: 0,
        era: 0,
        np: 0,
        ns: 0,
        nb: 0
      },
			{
        year: '0000',
        league: 'Name League',
        game: '01 sep, Name team - Name Team',
        pa: 0,
        r: 0,
        er: 0,
        h: 0,
        '2b': 0,
        '3b': 0,
        hr: 0,
        bb: 0,
        ibb: 0,
        hp: 0,
        sh: 0,
        sf: 0,
        so: 0,
        wp: 0,
        era: 0,
        np: 0,
        ns: 0,
        nb: 0
      },
			{
        year: '0000',
        league: 'Name League',
        game: '01 sep, Name team - Name Team',
        pa: 0,
        r: 0,
        er: 0,
        h: 0,
        '2b': 0,
        '3b': 0,
        hr: 0,
        bb: 0,
        ibb: 0,
        hp: 0,
        sh: 0,
        sf: 0,
        so: 0,
        wp: 0,
        era: 0,
        np: 0,
        ns: 0,
        nb: 0
      },
			{
        year: '0000',
        league: 'Name League',
        game: '01 sep, Name team - Name Team',
        pa: 0,
        r: 0,
        er: 0,
        h: 0,
        '2b': 0,
        '3b': 0,
        hr: 0,
        bb: 0,
        ibb: 0,
        hp: 0,
        sh: 0,
        sf: 0,
        so: 0,
        wp: 0,
        era: 0,
        np: 0,
        ns: 0,
        nb: 0
      },
			{
        year: '0000',
        league: 'Name League',
        game: '01 sep, Name team - Name Team',
        pa: 0,
        r: 0,
        er: 0,
        h: 0,
        '2b': 0,
        '3b': 0,
        hr: 0,
        bb: 0,
        ibb: 0,
        hp: 0,
        sh: 0,
        sf: 0,
        so: 0,
        wp: 0,
        era: 0,
        np: 0,
        ns: 0,
        nb: 0
      },
			{
        year: '0000',
        league: 'Name League',
        game: '01 sep, Name team - Name Team',
        pa: 0,
        r: 0,
        er: 0,
        h: 0,
        '2b': 0,
        '3b': 0,
        hr: 0,
        bb: 0,
        ibb: 0,
        hp: 0,
        sh: 0,
        sf: 0,
        so: 0,
        wp: 0,
        era: 0,
        np: 0,
        ns: 0,
        nb: 0
      },
		]
  };

  const TABLE_OPTIONS = ['Batting', 'Running'];

  const handleTableOptionClick = option => setTableType(option);
  return (
    <section>
      <div className='container'>
        <div className={cl.content}>
          <p className={cl.playerChr}>P | B/T: R/R | 6' 4" 220LBS | Age: 31</p>
          <div className={cl.dropWrapper}>
            <Dropdown
              title={tableType}
              options={TABLE_OPTIONS}
              currentOption={tableType}
              handleClick={handleTableOptionClick}
            />
          </div>
          {tableType === 'Batting' ? (
            <ContentBattingTable TABLE_DATA={TABLE_DATA} playerYears={playerYears} />
          ) : (
            <ContentPitchingTable TABLE_DATA={TABLE_DATA} playerYears={playerYears} />
          )}
        </div>
      </div>
    </section>
  );
};

export default Content;
