/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.10 scene.gltf --transform 
Files: scene.gltf [194.3KB] > scene-transformed.glb [45.82MB] (-23482%)
Author: DAS AUTO (https://sketchfab.com/das_auto)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/bmw-alpina-b12-e38-f6541aa49e284905a34fc205bd296e5e
Title: BMW Alpina B12 E38
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'
import Stadium from 'images/optimizedField.glb'

export default function Model(props) {
  const { nodes, materials } = useGLTF(Stadium)
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.L0_1_0_0.geometry}
        material={materials.L0_1_0_0_geom_mat}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.L0_0_0_0.geometry}
        material={materials.L0_0_0_0_geom_mat}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.L0_2_0_0.geometry}
        material={materials.L0_2_0_0_geom_mat}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.L0_0_1_0.geometry}
        material={materials.L0_0_1_0_geom_mat}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.L0_1_1_0.geometry}
        material={materials.L0_1_1_0_geom_mat}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.L0_2_1_0.geometry}
        material={materials.L0_2_1_0_geom_mat}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.L0_0_2_0.geometry}
        material={materials.L0_0_2_0_geom_mat}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.L0_1_2_0.geometry}
        material={materials.L0_1_2_0_geom_mat}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.L0_2_2_0.geometry}
        material={materials.L0_2_2_0_geom_mat}
      />
    </group>
  )
}

useGLTF.preload(Stadium)