/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.10 scene.gltf --transform 
Files: scene.gltf [194.3KB] > scene-transformed.glb [45.82MB] (-23482%)
Author: DAS AUTO (https://sketchfab.com/das_auto)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/bmw-alpina-b12-e38-f6541aa49e284905a34fc205bd296e5e
Title: BMW Alpina B12 E38
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import Car from 'images/scene-transformed.glb'

export default function Model(props) {
  const { nodes, materials } = useGLTF(Car)
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.bmw_alpina_b12_gauge_alpha_0.geometry} material={materials.gauge_alpha} position={[0, -0.018, 0]} />
      <mesh geometry={nodes.bmw_alpina_b12001_Matte__FF808040__prim_env_5_spec__0.geometry} material={materials.Matte__FF808040__prim_env_5_spec} position={[0, -0.018, 0]} rotation={[0.006, 0, 0]} />
      <mesh geometry={nodes.bmw_alpina_b12002_badge_cp_0.geometry} material={materials.badge_cp} position={[0, -0.018, 0]} />
      <mesh geometry={nodes.bmw_alpina_b12003_bump_plastic_0.geometry} material={materials.bump_plastic} position={[0, -0.018, 0]} rotation={[0.006, 0, 0]} />
      <mesh geometry={nodes.bmw_alpina_b12004_chrome001_0.geometry} material={materials['chrome.001']} position={[0, -0.018, 0]} rotation={[0.006, 0, 0]} />
      <mesh geometry={nodes.bmw_alpina_b12005_digital_gauge_0.geometry} material={materials.digital_gauge} position={[0, -0.018, 0]} />
      <mesh geometry={nodes.bmw_alpina_b12006_gauge_emissive001_0.geometry} material={materials['gauge_emissive.001']} position={[0, -0.018, 0]} />
      <mesh geometry={nodes.bmw_alpina_b12007_leather_0.geometry} material={materials.leather} position={[0, -0.018, 0]} rotation={[0.006, 0, 0]} />
      <mesh geometry={nodes.bmw_alpina_b12008_metal_pedals_0.geometry} material={materials.metal_pedals} position={[0, -0.018, 0]} />
      <mesh geometry={nodes.bmw_alpina_b12009_mottled001_0.geometry} material={materials['mottled.001']} position={[0, -0.018, 0]} rotation={[0.006, 0, 0]} />
      <mesh geometry={nodes.bmw_alpina_b12010_reflector_cp_0.geometry} material={materials.reflector_cp} position={[0, -0.018, 0]} />
      <mesh geometry={nodes.bmw_alpina_b12011_solid001_0.geometry} material={materials['solid.001']} position={[0, -0.018, 0]} rotation={[0.006, 0, 0]} />
      <mesh geometry={nodes.bmw_alpina_b12012_wood_0.geometry} material={materials.wood} position={[0, -0.018, 0]} rotation={[0.006, 0, 0]} />
      <mesh geometry={nodes.bmw_alpina_b12013_plastic002_0.geometry} material={materials['plastic.002']} position={[0, -0.018, 0]} rotation={[0.006, 0, 0]} />
      <mesh geometry={nodes.bmw_alpina_b12016_rim001_0.geometry} material={materials['rim.001']} position={[0, -0.001, 0]} />
      <mesh geometry={nodes.bmw_alpina_b12017_black002_0.geometry} material={materials['black.002']} position={[0, -0.018, 0]} rotation={[0.006, 0, 0]} />
      <mesh geometry={nodes.bmw_alpina_b12018_orangeglass_0.geometry} material={materials.orangeglass} position={[0, -0.018, 0]} />
      <mesh geometry={nodes.bmw_alpina_b12019_clearglass_0.geometry} material={materials.clearglass} position={[0, -0.018, 0]} rotation={[0.006, 0, 0]} />
      <mesh geometry={nodes.bmw_alpina_b12020_windowglass_0.geometry} material={materials.windowglass} position={[0, -0.018, 0]} rotation={[0.006, 0, 0]} />
      <mesh geometry={nodes.bmw_alpina_b12021_rear1_0.geometry} material={materials.rear1} position={[0, -0.018, 0]} rotation={[0.006, 0, 0]} />
      <mesh geometry={nodes.bmw_alpina_b12022_head1_0.geometry} material={materials.head1} position={[0, -0.018, 0]} rotation={[0.006, 0, 0]} />
      <mesh geometry={nodes.bmw_alpina_b12023_redglass_0.geometry} material={materials.redglass} position={[0, -0.018, 0]} />
      <mesh geometry={nodes.bmw_alpina_b12024_mirror001_0.geometry} material={materials['mirror.001']} position={[0, -0.018, 0]} />
      <mesh geometry={nodes.bmw_alpina_b12025_interior_0.geometry} material={materials.interior} position={[0, -0.018, 0]} rotation={[0.006, 0, 0]} />
      <mesh geometry={nodes.bmw_alpina_b12026_carpaint_0.geometry} material={materials.carpaint} position={[0, -0.018, 0]} rotation={[0.006, 0, 0]} />
      <mesh geometry={nodes.bmw_alpina_b12027_black1_0.geometry} material={materials.black1} position={[0, -0.018, 0]} rotation={[0.006, 0, 0]} />
      <mesh geometry={nodes.bmw_alpina_b12028_blue_0.geometry} material={materials.blue} position={[0, -0.018, 0]} rotation={[0.006, 0, 0]} />
      <mesh geometry={nodes.bmw_alpina_b12030_Default_Material_0.geometry} material={materials.Default_Material} position={[0, -0.018, 0]} rotation={[0.006, 0, 0]} />
      <mesh geometry={nodes.bmw_alpina_b12031_plastic2_0.geometry} material={materials.plastic2} position={[0, -0.018, 0]} />
      <mesh geometry={nodes.bmw_alpina_b12032_emblem_0.geometry} material={materials.emblem} position={[0, -0.018, 0]} />
      <mesh geometry={nodes.bmw_alpina_b12033_tire_0.geometry} material={materials.tire} position={[0, -0.001, 0]} />
      <mesh geometry={nodes.bmw_alpina_b12034_brakedisk_0.geometry} material={materials.brakedisk} position={[0, -0.001, 0]} />
      <mesh geometry={nodes.bmw_alpina_b12038_caliper_0.geometry} material={materials.caliper} position={[0, -0.001, 0]} />
      <mesh geometry={nodes['��������������_����������������_0'].geometry} material={materials.material} position={[0.862, 0.379, 1.627]} rotation={[-0.086, 1.03, -1.508]} scale={[0.024, 0.024, 0.003]} />
    </group>
  )
}

useGLTF.preload(Car)