/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.10 scene.gltf --transform 
Files: scene.gltf [194.3KB] > scene-transformed.glb [45.82MB] (-23482%)
Author: DAS AUTO (https://sketchfab.com/das_auto)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/bmw-alpina-b12-e38-f6541aa49e284905a34fc205bd296e5e
Title: BMW Alpina B12 E38
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import Stadium from 'images/optimizedField.glb'

export default function Model(props) {
  const { nodes, materials } = useGLTF(Stadium)
  return (
    <group {...props} dispose={null}>
      <group rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Mesh002.geometry}
          material={materials.SEA_Greyscale}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Mesh002_1.geometry}
          material={materials.Ads_Padding}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Mesh002_2.geometry}
          material={materials.SEA_Field}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Mesh002_3.geometry}
          material={materials.SEA_Infield}
        />
      </group>
    </group>
  )
}

useGLTF.preload(Stadium)